### ISSUE TITLE
Entrega Sesión 7 - Tarea Individual y Tarea de Grupo

### ISSUE THREAD

**Issue by ghost** [pedroprieto/curso-github#4]
**Tarea Individual**

Captura del repositorio creado para tí en la organización

![Tarea 1 - Grupo - GitHub Manuel Enguidanos](https://github.com/pedroprieto/curso-github/assets/157827963/71a1798c-b1ca-42b2-b545-486d5fa52d61)

Captura de la vista de la tarea en GitHub Classroom donde aparece el enlace a tu repositorio en mi usuario

![Tarea 1 - Grupo - GitHub Classroom](https://github.com/pedroprieto/curso-github/assets/157827963/875402c1-7d30-4ce6-9919-457b8f17d145)

**Tarea Grupo**

Captura del repositorio creado para mi equipo en la organización

![Tarea 2 - Grupo - GitHub Manuel Enguidanos](https://github.com/pedroprieto/curso-github/assets/157827963/dbfe1084-69db-4e07-9571-05f5a06c469f)

Captura de la vista de la tarea en GitHub Classroom donde aparece el enlace a tu repositorio en mi usuario

![Tarea 2 - Grupo - GitHub Classroom](https://github.com/pedroprieto/curso-github/assets/157827963/90f40904-be83-4b77-8d54-a5470efe8f6d)

**Comment by pedroprieto** [comment]
Buen trabajo! Todo perfecto! :clap:

Con esto terminas todo :blush: Espero que el curso haya sido de tu agrado y que te sea de utilidad en tus clases. Para cualquier cosa, por aquí estoy.

Un saludo!!

**Comment by ghost** [comment]
Muy interesante todo lo que hemos visto, lo pondremos en práctica seguro, muchas gracias por todo y un placer, lo mismo digo para cualquier cosa.... ahí estamos.

          Un saludo!!!

**Comment by pedroprieto** [comment]
Muchas gracias por tus palabras, Manuel!! :blush:  Ánimo pues!! :+1:
